apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - image: adewaleda/udagram-api-feed:v12
          name: backend-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "2000Mi"
              cpu: "750m"
            limits:
              memory: "4000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
